Makefile
Step definitions copied from notifications-api Makefile
=> Add cf-login and cf-rollback make targets used by CI pipeline

manifest.yml.j2
Removed the hostname from the dd-api  as the public facing site will be the frontend app.
=> Removed the hostname from the dd-api 

application.py
testing zdt rollback stuff. don't push this to production!
=> add deliberately broken build

application.py
Reverts alphagov/document-download-api#56
oh no what a silly mistake! i should never have committed this! 
that was silly of me
=> Revert "add deliberately broken build"

requirements-app.txt, requirements-dev.txt, requirements.txt
Upgraded Flask, notifications-utils, and most of the development dependencies. This fixes the security warnings for Jinja2 and urllib3.
=> Upgrade dependencies

Makefile, requirements-dev.txt
=> Remove coveralls

.gitignore, Makefile, app/config.py, app/upload/errors.py, app/upload/views.py, app/utils/store.py, requirements-app.txt, requirements-dev.txt, requirements.txt, tests/upload/test_views.py, tests/utils/test_store.py
mimetypes taken from https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types
and a few other quality of life tweaks
=> support .doc and .docx

app/upload/views.py, tests/upload/test_views.py
=> use did not, not didn't

requirements-app.txt, requirements.txt
gunicorn in particular had vulns
=> bump gunicorn and boto

Makefile
This makes it easy to see what your options are when just running the
make command.
I have only done the commands that I think developers will care to know
about during local development.
=> Add further help commands to makefile

app/upload/views.py
Tests for external contributor PR
=> Remove FileStorage

app/download/views.py, tests/download/test_views.py
=> Concourse test pr 129

.github/pull_request_template.md
To let people know what will happen when they click merge and provide
them information on how to stop that happening
=> Add pull request template mentioning CD

app/utils/__init__.py, tests/utils/test_mime_types.py
https://www.pivotaltracker.com/story/show/179434823
---
=> Extend docx / zip bug fix to cope with xlsx files

.github/pull_request_template.md
=> Fix manual links

requirements.txt
=> Bump dependencies to address pyup vulnerabilities

requirements.in, requirements.txt
https://github.com/pallets/werkzeug/security/advisories/GHSA-xg9f-g7g7-2323
---
=> Bump werkzeug to address vulnerability

app/utils/store.py, tests/utils/test_store.py
If we try to GetObjectTagging on an expired document (eg deleted due to the retention period lifecycle), we get an error. Let's catch this and suppress it appropriately so that the user sees a 'this file is no longer available' page.
---
=> Catch errors from expired documents

.flake8, .pre-commit-config.yaml, Makefile, app/upload/views.py, app/utils/store.py, pyproject.toml, requirements_for_test.txt, setup.cfg
=> Add ruff, remove isort+flake8

requirements.in, requirements.txt
This will ensure we always get the correct dependencies installed.
---
=> Include `flask` extra for sentry

manifest.yml.j2
=> Use the correct variable name for the new route

.pre-commit-config.yaml, app/download/views.py, app/utils/antivirus.py, app/utils/store.py, pyproject.toml, requirements.in, requirements.txt, requirements_for_test.txt
=>  Bump utils to 65.0.0

scripts/create-droplet.sh
=> Typo in create-droplet script

.pre-commit-config.yaml, app/download/views.py, requirements_for_test.txt, tests/conftest.py, tests/upload/test_views.py
=> Bump black to 23.10.1

app/config.py
This changeset ended up in
https://github.com/alphagov/document-download-api/pull/285 somehow. It shouldn't be there, and breaks things.
---
=> Remove incorrect changes

app/config.py, app/download/views.py, tests/download/test_views.py
=> This adds the platform to the response on _status

app/download/views.py
=> This changes the cache behaviour of the status page

gunicorn_config.py, requirements.in, requirements.txt
https://trello.com/c/QfqBdvUK/687-structured-logging-from-gunicorn
Reverts #324 and bumps to a fixed utils version.
---
=> gunicorn structured logging v2

requirements.in, requirements.txt
Closes #326
Closes #327 
Closes #328 
Closes #330 
Closes #331 
Closes #333 
---
=> Resolve dependabot PRs

app/download/views.py, app/upload/views.py, app/utils/validation.py, requirements.in, requirements.txt, tests/utils/test_validation.py
some changes to import paths for recipient validation
---
=> bump utils

requirements.in, requirements.txt
=> Restore botocore[crt]

.gitignore, .pre-commit-config.yaml, Makefile, docker/Dockerfile, pyproject.toml, requirements.txt, requirements_for_test_common.txt
So that every time you bump the utils version you get the correct corresponding files and the build is more reproduceable.
---
=> Copy common config files from utils in freeze step

app/utils/store.py, tests/utils/test_store.py
https://trello.com/c/Ndw2IbUs/1109-make-document-download-api-deny-access-to-documents-that-are-determined-to-be-expired-based-directly-on-their-tags
This is implemented in a way that calculates the expiry date separately through lifecycle-rule-based S3 headers and directly through the tags on the S3 objects. The earliest expiry date is then chosen. Each method of calculation is written with quite a few fallbacks with the intention to be as robust as possible, but either can fail and will in that case fall back to the other calculation. If neither calculation method is successful (absolute worst case scenario, 3 mechanisms would need to have failed) it will allow the request, as the worst that *should* be able to happen in this case is showing a document that should have been deleted up …
=> DocumentStore: fallback to using s3 tags to determine expiration

README.md, docker/Dockerfile
this is to test CI only for now - don't review yet!
=> Upgrade Python version to 3.13 for document-download-api
