alphagov/document-download-api

Makefile, app/__init__.py, app/config.py, app/download/views.py, app/upload/views.py, app/utils/urls.py, manifest.yml.j2, requirements.txt, scripts/run_app_paas.sh, tests/download/test_views.py, tests/utils/test_urls.py
If manifest template is missing variables jinja-cli will output an exception to stderr and exit without printing anything to stdout.
This makes `cf push` run with an empty manifest, which it treats as a valid call so it proceeds to deploy an app without any route or environment variable configuration.
To avoid this we redirect stderr to sdout when generating a manifest, so if an exception happens it is written to the manifest and since it's invalid YAML `cf push` will fail the release right away.
The problem with this approach is that the exception no longer appears in the command output or CI logs, so it's not obvious what is wrong with the manifest generation.
An alternative approach would be to not specify application name in the `cf push` command, making it invalid to use with an …
=> Logging and request IDs

Makefile, app/__init__.py, app/config.py, gunicorn_config.py, manifest.yml.j2, requirements.txt
Adds a /metrics endpoint that collects request times, codes and errors and can be scraped by Prometheus.
This moves gunicorn configuration to a separate file to support prometheus client multiprocess mode.
Prometheus service broker expects application route to match <app_name>.cloudapps.digital and currently doesn't support custom routes.
Since we can't use the same route across different spaces we need to add CF_SPACE to the application name (so eg instead of `api` we'll have `api-preview`).
Note: this requires pushing the app with `make cf-push` to each space to create the initial instance (otherwise cf-deploy will fail to find an existing app) and deleting the existing `document-download-api` apps in all spaces afterwards.
=> Prometheus metrics

manifest.yml.j2
Adds a make target to create the prometheus service broker and give
it space auditor permissions.
Adds the created service to the document-download-api manifest, so
that it's bound to the new app created by the zero-downtime release
process.
=> Bind Prometheus service broker to the app during release

.flake8, Dockerfile, Makefile, app/config.py, app/upload/views.py, app/utils/__init__.py, requirements-dev.txt, requirements.txt, tests/upload/test_views.py
Identifies the uploaded file type using libmagic and checks if it's included in a list of allowed file types.
This allows us to set the correct mimetype on the S3 object and stops users from uploading unsupported document types.
File identification is based on 'magic patterns' used by `file` command, so while it should identify all valid PDF files as PDF it doesn't guarantee that a file is valid and can be opened by a PDF reader. This should be enough to inform users about our supported document types and prevent accidental uploads of unsupported formats, but doesn't protect against a user trying to send an unsupported file by masking it as one of the allowed types.
=> Check uploaded document matches one of the allowed file types

manifest.yml.j2
The hostname is still needed to generate the URL link to send via the notification. So its just the  route that is not needed which gives it its public hostname.
=> Added back the hostname decision block

manifest.yml.j2
Users will download the document file directly from the API to avoid piping the data through the frontend app.
We need to make the download endpoint available through the public service.gov.uk domain. We bind `/services` route to the API, which includes the download route. This means that Document Download frontend will have to avoid using the `/services` prefix for any of its URLs as any requests to them would be routed to the API instead.
API itself isn't restricted to only use `/services` prefix, since other apps can call API endpoints using the .cloudapps.digital subdomain.
=> Map the download route to a public domain

app/config.py, app/upload/__init__.py, app/upload/errors.py, tests/upload/test_views.py
Setting MAX_CONTENT_LENGTH configuration option makes Flask return a 413 response when the request Content-Length exceeds the setting value.
We're setting an error handler for 413 status code to return a JSON error response, but since Flask will close the connection before reading the full response (which is the desired behaviour in order to avoid running out of memory/disk space by fetching large requests) depending on the client implementation in might not get displayed.
=> Limit uploaded document size to 2Mb

Makefile, app/__init__.py, application.py, manifest.yml.j2, pytest.ini, requirements-dev.txt, tests/conftest.py
Flask 1.0 introduced ENV config variable (set from FLASK_ENV env
variable) that is used by flask and extensions to set things like
debug mode.
Switching to it allows us to standardise the approach across our
apps and base the config selection on application.env instead of
the custom environment variable.
=> Replace ENVIRONMENT with FLASK_ENV

Makefile, manifest.yml.j2
Prometheus PaaS service broker didn't support custom app routes, so we had to rename document download apps to use unique names in each environment. This is inconsistent with what other notify apps do and doesn't work well with metrics-exporter metrics (since they expect the same app name for all spaces).
Now that custom route support has been added to the service broker we can rename the apps to use the same name. Service broker will use the first route to scrape the metrics page.
This reverts 077243b
=> Use the same app name across all PaaS spaces

Makefile, manifest.yml.j2
Our new service domain is documents.service.gov.uk, so updating preview and staging subdomains to match it.
This also renames the cdn-route service to both match the domain name and allow switching the service without destroying the CDN first.
=> Update subdomains to documents.*

app/download/views.py, tests/download/test_views.py
Setting the X-Robots-Tag header to `noindex, nofollow` prevents search engines from indexing the page or following any links to other pages.
This is different from robots.txt (which prevents pages from being crawled by search engines) since it also stops any documents linked from other websites from showing up in search results.
=> Prevent documents from being indexed by search engines

app/config.py, tests/upload/test_views.py
We want to allow services to upload CSV files. CSVs are mostly recognised as plain text by libmagic, so we have to allow all text files at once.
Adding text/csv covers any edge cases that might be recognised by libmagic as well as make the error message more clear (specifically mentioning that CSVs are allowed).
=> Allow CSV document uploads

runtime.txt
PaaS will be updating the python-buildpack to 1.6.20. Python 3.6.4 was dropped in the 1.6.19: https://github.com/cloudfoundry/python-buildpack/releases/tag/v1.6.19
=> Bump runtime version to 3.6.6

app/config.py, tests/upload/test_views.py
MAX_CONTENT_LENGTH is checking the value of the request's Content-
Length header. This is generally slightly larger than the actual
uploaded file size since the multipart POST request body will include
data boundaries and Content-Type/Content-Disposition headers for
each file. It doesn't have a set overhead size since it depends on
the client implementation and the uploaded file name.
We don't really care if a file is slightly larger than 2MB, but we
need to allow any files that are below 2MB (since that's what users
would expect based on our documentation) so we add a 1KB buffer to
the content length check, which should cover the size of the
multipart form wrapper.
=> Add some tolerance to the max document size check

requirements-app.txt, requirements.txt
awscli 1.15 requires botocore 1.10, but 1.12 is installed instead.
Since pip installs the first package version that it comes across,
awscli 1.15 is picked up from notification-utils dependencies, but
botocore is taken from boto3.
Moving utils after awscli-cwlogs (matching the order in notifications-api
requirements) makes pip install the latest versions of both awscli and
botocore, which should be compatible with each other.
=> Fix awscli/botocore version incompatibility

requirements-app.txt, requirements.txt
Downgrades gunicorn to 19.7.1 to fix eventlet patching and updates
insecure dependencies (requests and bleach).
=> Update notification-utils to the latest version

runtime.txt
Python patch releases are pretty stable and since PaaS buildpacks deprecate older patch versions quite regularly the recommended approach is to not pin the individual 3.6.x release.
=> Only pin python runtime to the minor 3.6 version

Makefile, Procfile, manifest.yml.j2
Replace our own zero downtime blue-green kludge with new cloudfoundry builtin mechanisms
We're currently using our own handrolled zero downtime deploy script, it works as follows
1. Rename app to "{APP_NAME}-rollback"
2. Push new code to regular app name
3. Scale new app to have the same number of instances as the old app.
4. Assert there are no crash events on the new app.
5. Stop and delete the old app.
We've seen problems at step 5 - both the new app and the old app are serving traffic/processing tasks at this point, and we've often seen "permission denied for relationship" psycopg2 errors - these are because when you delete an app, cf removes the user from the database. Additionally, I'm not very convinced at how robust our crash recovery rollback process is - it appears to stop the …
=> deploy with zero downtime deploy

manifest.yml.j2
Otherwise, you can't do a deploy while an existing deploy is in progress if the app has been scaled to a different amount, since the first step of the deploy is to apply the manifest, which will try and scale the app.
We let the autoscaler take care of the instance count for apps that care about it anyway.
=> Don't specify instance counts in manifests

Makefile
pushing an app involves two steps: applying the manifest, and pushing the source code.
Applying a manifest will _immediately_ scale the app to have whatever instance count, memory and disk quota the manifest says. It'll also apply environment variable changes to the next droplet (ie: next push).
zdt deploys block scale actions, and as such, if there's a deploy under way, you can't push a new build. Failing deploys carry on after cf-cli returns a non-zero build, so we need to cancel previous deploys before starting another.
There is a risk introduced with this - if, for whatever reason, two builds were run in parallel, specifically, one push happens on top of another push, when you cancel the second one, it'll roll back to the first push's droplet, rather than the stable state from before …
=> cancel any existing deploy before pushing

Makefile
you can't scale an app while it's deploying. If a build fails, it may take us a while to identify the cause, create a fix and get that deployed, and it would be problematic if we couldn't scale the app for that time.
So, on rollback, cancel the deploy. Still keep the cancel step in the deploy phase, JustInCase™. It shouldn't ever trip now, but if jenkins died unexpectedly and couldn't hit the `make cf-rollback` command we'll still need it.
=> cancel zdt deploy on rollback

requirements-app.txt, requirements.txt
Version 33.0.0 brings in a version of PyYAML without any security vulnerabilities.
=> Bump notifications-utils

manifest.yml.j2
We only run one instance in production. This should be 2 for high
availability
=> Run two instances instead of one

.pyup.yml
As per https://pyup.io/docs/bot/config/#specify-files, this means pyup
will not update requirements.txt under general circumstances. The
exception will be for security updates - although we won't merge the
security update as is, it will hopefully be the prompt for us to run
make freeze-requirements which will likely solve the insecure
requirement.
=> Don't let pyup update requirements.txt apart from for security

app/download/views.py, app/utils/store.py, tests/download/test_views.py, tests/utils/test_store.py
We want a way of knowing if a file is in S3 so that document-dowload-frontend can display a different page to users instead of showing them a link to the document. This adds a method to the `DocumentStore` class to check and a new endpoint to display the result.
[Pivotal story](https://www.pivotaltracker.com/story/show/172199088)
=> Add endpoint to check if file is in S3

app/upload/views.py
Please see: https://github.com/alphagov/notifications-api/pull/2836#issuecomment-627460349
I tried to investigate this but cannot quite figure out why this is not working as it should. 
Given that `FileStorage` is a [thin wrapper](https://github.com/pallets/werkzeug/blob/master/src/werkzeug/datastructures.py#L2964) around the underlying stream here, this should be (1) safe and (2) it works.
=> Remove FileStorage

app/download/views.py, tests/download/test_views.py
This PR ensures that download responses for CSV files have an explicit `Content-Disposition: attachment; filename=<uuid>.csv` header set.
This is necessary as browser handling for responses for CSV responses from the download API endpoint was a little spotty.  The experience for the user would vary across OS/browser combinations, e.g. opening spreadsheet applications, downloading a file as <uuid>.txt, downloading a file with no extension or just showing the raw text in the browser.  
By making this an explicit download, we can ensure that users always download a `<uuid>.csv` file.
I have tested this on Linux (Chrome and Firefox) and Windows (Chrome, IE11, Edge) - downloads occur as expected.
=> Set CSV download Content-Disposition

app/download/views.py, tests/download/test_views.py
https://www.pivotaltracker.com/n/projects/1443052
We have complaints from users that when they click the link to download
an rtf file it is shown as raw text in their browser as there is no
'Content-Disposition' header. This commit does similar to how we treat
CSVs and adds the header such that they will download for a user.
Note when testing. This problem does not appear to exist on my mac
(regardless of if I use Safari, Chrome or Edge) so it likely a
combination of browser and OS system so I have not been able to
replicate myself but have taken the same approach as we did for CSVs and
tested that it does at least not break things.
=> Force download of rtf files rather than inline

Makefile
This was removed accidentally in [1] and is a reserved variable in
Makefiles to set the running shell [2].
[1]: https://github.com/alphagov/document-download-api/pull/159
[2]: https://www.gnu.org/software/make/manual/html_node/Choosing-the-Shell.html
---
=> Fix not using 'bash' to run Makefile commands

app/config.py, tests/upload/test_views.py
https://www.pivotaltracker.com/story/show/177188288
This has been requested by our users. While there are many Excel
formats we could support - macro-enabled, templated, binary - we
want to limit the set to those with an established a user need.
I've tested this manually with a sample .xlsx file provided by the
user, and can confirm it uploads/downloads as expected.
---
=> Allow uploading simple Excel spreadsheets

app/config.py, tests/upload/test_views.py, tests/utils/test_mime_types.py
https://www.pivotaltracker.com/story/show/177188288
This reverts commit a1b425e4187d0ee9a9787bf18c325b9810b5020d. After
testing with different browsers we discovered an issue where the file
extension is missing for .xlsx and .docx attachments downloaded via
MS Edge, which prevents them being opened [1]. Since .xlsx is a recent
addition, we decided to remove support for it until we fix the issue.
I've left the test for the MIME type in as it's still valid for us to
check we can infer it correctly, whether it's allowed or not.
[1]: https://github.com/alphagov/document-download-api/pull/162#issuecomment-803006654
---
For more information, including how to check this deployment on preview or staging …
=> Revert "Allow uploading simple Excel spreadsheets"

app/config.py, app/download/views.py, app/upload/views.py, app/utils/store.py, app/utils/urls.py, tests/download/test_views.py, tests/upload/test_views.py, tests/utils/test_store.py, tests/utils/test_urls.py
https://www.pivotaltracker.com/story/show/177188288
This prepares to fixe an issue with not being able to open some attachments
when downloaded with certain browsers on Windows. We'll need a PR in the 
frontend app in order to make use of it.
Please see the commit messages for more details.
---
=> Allow optional extension when downloading files

app/download/views.py, tests/download/test_views.py
https://www.pivotaltracker.com/story/show/177188288
Depends on: https://github.com/alphagov/document-download-frontend/pull/86
This is superseded by the new 'document' value in the response.
---
=> Remove redundant 'file_exists' response flag

app/download/views.py
https://www.pivotaltracker.com/story/show/177925366
After waiting about a month, the old (non-extension) route is still
used, albeit at low volume. Since removing the route would effectively
make the documents unavailable to the user (assuming they can't find
the original email link), we should keep it for the time being.
Some supporting stats (last 7 days):
- Total requests: 149.
- Total distinct requests (by IP): 74.
Previously we had thousands of request per day.
---
For more information, including how to check this deployment on preview or staging first before it goes to production, see our [team wiki section on continuous deployment](https://github.com/alphagov/notifications-manuals/wiki/Deployi …
=> Add comment to explain duplicate route

app/config.py, tests/upload/test_views.py, tests/utils/test_mime_types.py
Reasoning:
While CSV is preferable to XLSX, we occasionally get requests
to support XLSX, and each time end up spending time discussing
if there is a strong enough case to support it.
We decided it is more efficient to do that work than to keep
discussing it.
Ticket:  https://www.pivotaltracker.com/story/show/177188288
---
=> Start supporting XLSX files

requirements.in, requirements.txt
https://www.pivotaltracker.com/story/show/181498273
The changelog indicates this is due to a new Homebrew lib dir [^1].
We may as well upgrade to the latest version - all the other changes
look benign.
[^1]: https://github.com/ahupp/python-magic/blob/master/CHANGELOG#L15
---
=> Fix "ImportError: failed to find libmagic"

requirements.in, requirements.txt
https://www.pivotaltracker.com/story/show/181498273
This repo has fallen a *long* way behind. None of the changes [^1] in
utils affect this repo, though: it just uses the logging, request and
base64 functions from it - none of which have changed.
[^1]: https://github.com/alphagov/notifications-utils/pull/955
---
=> Bump -utils to 55.1.1

app/download/views.py, requirements.in, requirements.txt, requirements_for_test.txt, tests/download/test_views.py
**Bump Flask to 2.1.1** 
This required one argument to `send_file` to be renamed to avoid a deprecation warning.
The other change seen, which I can't find any reference to in changelogs for Flask or Werkzeug, is that the `Expires` response header is no longer returned and a `Date` header is returned instead.
Also bumps the test dependencies.
---
=> Bump Flask and the test dependencies

requirements.in, requirements.txt
https://www.pivotaltracker.com/story/show/181588331
This required bumping the minimum version of boto3 with:
pip-compile -P awscli requirements.in
I haven't looked into the awscli/boto3/botocore changes due to the
high churn on those libraries. Given they're minor changes we can
assume they are benign. s3transfer changes are also benign [^1]
This is also a good opportunity to remove the redundant egg spec in
the requirements, like we have in other repos.
[^1]: https://github.com/boto/s3transfer/blob/develop/CHANGELOG.rst
---
For more information, including how to check this deployment on preview or staging first before it goes to production, see our [team wiki section on continuous …
=> Bump utils to 55.1.4

requirements.in, requirements.txt
Copies [the approach taken by notifications-api](https://github.com/alphagov/notifications-api/pull/3466) to bump gunicorn and avoid the eventlet vulnerability
Upgrades notifcations-utils to bring in secure pypdf2 version
Upgrades urllib3 to a secure version
---
=> Upgrade packages to get rid of security warnings

app/download/views.py, tests/download/test_views.py
The referrer-policy header defines when and what should be sent
in the `Referer` header when a http request is made from clicking
a link on a page.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
When serving document files in the browser we
do not currently set the `Referrer-Policy` header. This means the
browser default is generally followed. Over the past few years browser
defaults have been changed to `strict-origin-when-cross-origin`
however this is quite a recent change and before that most used
`no-referrer-when-downgrade`.
https://developer.chrome.com/blog/referrer-policy-new-chrome-default/
This means that when clicking on any links in pdf documents served
on documents.service.gov.uk, for users using older versions of browsers
we will send the full URL …
=> Add HTTP `Referrer-Policy' as `no-referrer` to download views

manifest.yml.j2
We have migrated to our own Prometheus metrics stack and no
longer require the gds-prometheus backing service (the service
instance is named notify-prometheus in all environments).
We have been running the new metrics stack alongside the existing
service for a few weeks and have tested and correlated collected
metrics in both systems for correctness.
Changes to the manifest are non-destructive so the service will
need to be manually unbound in each environment.
`cf unbind-service APP_NAME SERVICE_INSTANCE`
=> Remove notify-prometheus service binding

app/upload/views.py, tests/upload/test_views.py
The `.upload_document` endpoint was supporting content types of either 'application/json' or 'multipart/form-data' while we changed how we send files from API to document-download-api. We can now drop support for 'multipart/form-data' content since all data from API is now sent as json - https://github.com/alphagov/notifications-api/pull/2836.
Making this change helps simplify the tests for [the later story to adjust file sizes that can be uploaded](https://www.pivotaltracker.com/story/show/180461433)
---
For more information, including how to check this deployment on preview or staging first before it goes to production, see our [team wiki section on continuous …
=> Remove unused code from `.upload_document` endpoint

app/utils/__init__.py, tests/utils/test_mime_types.py
paas python buildpack has an old version of libmagic (5.32, you can check by running `file --version`).
We've seen a case where someone is trying to send a spreadsheet and libmagic identifies it as 'Microsoft OOXML', but when you ask for its mimetype it returns "application/octet-stream" (ie: a generic unknown binary blob). Using more up-to-date versions of libmagic on my local machine, it's identified as 'Microsoft Excel 2007+', with the mimetype correctly being 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'.
So, to mitigate this, just check octet-streams as well as application/zip to see if the might be a secret xlsx/docx file. As a reminder, xlsx/docx are zip files under the hood and we check by getting the file list for them and looking for a specific file that is …
=> check octet-stream as well as zip in case they are docx/xlsx

app/upload/views.py, tests/upload/test_views.py
To check the file type we load the file into memory and inspect it. We
probably shouldn't do this before we've scanned the file and are
confident it's safe.
---
=> Run antivirus scan before checking file type

app/upload/views.py, app/utils/store.py, requirements.in, requirements.txt, tests/upload/test_views.py, tests/utils/test_store.py
If verification_email present in request json.
This is done so we can protect the documents from being inadvertently shared to pages like internet archive or wayback machine. User will have to confirm that they are the one meant to access the file by entering their email address. This is not as strong as password protection, but enough for the purpose.
For hashing algorithm, we chose Argon2ID based on:
https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#password-hashing-algorithms
The above docs also provided us with a choice of parameters to use.
Our memory usage is higher than our CPU usage so we chose the parameters based on that. We also explicitly set hash length, based on argon2 docs: https://argon2-cffi.readthedocs.io/en/stable/parameters.html
---
🚨⚠️ …
=> Upload hashed recipient email to S3 with document as metadata

app/utils/store.py, tests/utils/test_store.py
When we query a document's metadata, let's also return whether or not
the document has a hashed email stored against it. If it does, then
indicate that the document requires the email confirmation flow.
Ticket: https://www.pivotaltracker.com/n/projects/1443052/stories/182952340
---
=> Return `verify_email` in document metadata

.gitignore, app/download/views.py, app/utils/hasher.py, app/utils/store.py, requirements_for_test.txt, tests/download/test_views.py, tests/utils/test_hasher.py, tests/utils/test_store.py
This endpoint will be used to check that a user-submitted email address
matches the hashed one we have stored against the document in S3. If it
matches, we will return a signed blob of data encoding the service id
and document id which the frontend will store as a cookie on the user's
client. This will then be sent by the client when they try to access the
final file download URL, proving that they have successfully gone
through the authentication flow.
---
For more information, including how to check this deployment on preview or staging first before it goes to production, see our [team wiki section on deployment](https://github.com/alphagov/notifications-manuals/wiki/Merging-and-deploying#deploymen …
=> Add `/authenticate` endpoint for documents

.pre-commit-config.yaml, README.md, requirements_for_test.txt
We can offer pre-commit hooks to developers so that it's not possible
to commit code that breaks some basic formatting conventions.
The provided hooks for flake8 and isort will also fix issues
automatically, but reject the initial commit. Generally you can just add
the changes that the hooks have made, and then commit again, to accept
the automated fixes.
This change will do nothing by default - developers will need to opt-in
by installing the hooks.
Example:
```
sam:~/work/gds/document-download-api [SW-pre-commit]$ git commit -a
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check yaml...........................................(no files to check)Skipped
debug statements …
```
=> Add pre-commit hooks

app/download/views.py, tests/download/test_views.py
We've implemented the verify_email return value on the document store
but aren't currently passing it out of the API response. Let's add this
so that the frontend can properly toggle on whether verification is
required or not.
---
=> Add verify_email param to API return

app/download/views.py, app/utils/store.py, tests/download/test_views.py, tests/utils/test_store.py
https://www.pivotaltracker.com/n/projects/1443052/stories/183012123
This is one part of the above story which will allow the frontend to display how big the file is for the user before they download it.
This is how the frontend will use it - https://github.com/alphagov/document-download-frontend/pull/136
---
=> Add size in bytes of file when getting metadata

app/download/views.py, app/upload/views.py, app/utils/store.py, app/utils/validation.py, tests/download/test_views.py, tests/upload/test_views.py, tests/utils/test_store.py, tests/utils/test_validation.py
We prefer the word `confirm` in our documentation and guidance, so let's keep the codebase consistent with that.
---
=> Rename `verification_email` to `confirmation_email`

app/download/views.py, tests/download/test_views.py
This is so the frontend can show what type of file the user will be downloading.
I did consider sending the mimetype or the pretty file type from the API instead of the file extension. I decided to go for the file extension as
- the file extension is already information the API exposes when providing a direct link to the file
- the pretty file type, ie 'text file' or 'Microsoft Word document' feels too presentational to be the responsibility of the API
- the mimetype is more complex than the file extension to read and understand and so this makes it simpler for the frontend to use
---
For more information, including how to check this deployment on preview or staging first before it goes to …
=> Add file extension to document metadata route

app/download/views.py, app/utils/signed_data.py, app/utils/store.py, requirements_for_test.txt, tests/download/test_views.py, tests/utils/test_signed_data.py, tests/utils/test_store.py
We authenticate users' emails with the prompt on the frontend, however, when the user clicks the link to actually download the file that's served straight from the document download API. This PR ensures that user has the cookie set earlier.
As a reminder, the cookie is set here and contains the service id and document id of the authorised document, as signed by the API[^1]. It's set on the cookie under the `document_access_signed_data`key[^2]. Because the document is served on the same domain as the admin pages, the cookie gets passed along to the api app no problem.
The flow goes as follows:
* verify the document exists and the key exists
* if the document is not authorised (as in: if it doesn't have a  hashed email in the s3 metadata)
- **continue**
* otherwise, check for the cookie.
* …
=> Check signed data from the cookie when downloading files

app/utils/store.py
Adds some logging info to document-download-api when enabling the email confirmation or setting a custom retention period, which will help in case we need to investigate anything in the coming days/weeks.
---
=> Add logging around new doc download flows

app/download/views.py, app/utils/store.py, tests/download/test_views.py, tests/utils/test_store.py
Add `available_until` information to the returned metadata about a stored file. Once this is in, the document-download-frontend can display a message on the file download page showing how long the file will be available for.
Ticket: https://trello.com/c/kbjPobxv/13-add-date-of-file-expiry-to-doc-download-page-and-tweak-wording
---
=> Get expiry date from metadata

app/upload/views.py, tests/upload/test_views.py
At the moment, if a user sends us `file` data that isn't base64 encoded (eg isn't in the ascii charset) then we are throwing a 500. Lately we've had this error coming through in batches, which we assume is happening because the user can't recover from the error because we aren't explaining what's wrong. Let's return a better error telling them to base64 encode the file.
---
=> Return 400 (not 500) on non-ascii document

tests/utils/test_hasher.py
In CI/CD, if it's particularly busy, a single test run can have wildly fluctuating timings. Hypothesis doesn't like this by default and will fail the test. Let's not do that, because it makes the test very flaky.
---
=> Don't fail on slower test results

.pyup.yml
PyUp docs:
```
requirements:
- requirements/staging.txt:
update: all
pin: True
- requirements/dev.txt:
update: False
- requirements/prod.txt:
update: insecure
pin: True
```
Despite their own documentation implying settings configured at a global level apply everywhere, it's not true.
---
=> Fix PyUp insecure-only version bumps. #4442

Makefile, app/__init__.py, manifest.yml.j2, pytest.ini
flask_env is deprecated, so when we use it for running locally, use flask_debug to get autoreloads and stack trace, and when we use it for determining which environment we're on use NOTIFY_ENVIRONMENT instead
---
=> replace FLASK_ENV with NOTIFY_ENVIRONMENT and FLASK_DEBUG

Makefile, docker/Dockerfile, scripts/run_locally_with_docker.sh
The dockerfile copies https://github.com/alphagov/notifications-api/blob/main/docker/Dockerfile very closely. The main differences are
- libmagic-dev is needed as mentioned in the README for this repo
- no entrypoint script like the API because there will only be one app that we run from this docker image, not multiple like the API
I've also copied the pattern of the API with scripts/run_locally_with_docker.sh which seems OK but we can adapt later if we need to.
Worth pointing out that we don't have any instructions in the README for this repo about what environment variables are needed to run the app, in particular it appears to need at least `NOTIFY_ENVIRONMENT` but I haven't tried to document this as part of this PR. For the time being you will need to remember to pass these …
=> Add dockerfile and ability to run locally using docker

.cfignore, app/download/views.py, app/utils/store.py, tests/utils/test_store.py
At the moment we have a convoluted process for blocking access to
published documents that involves an S3 bucket/object policy. This isn't
efficient or scalable (bucket policies can be at most 20kb, so
eventually this will just plain be impossible).
Let's instead allow a tag to restrict access to the file. We check for
this tag before attempting any other operations on the S3 object.
Once this is released we will be able to (still via the AWS console/boto) add a `blocked=true` tag to any objects we want to stop being downloaded, which is far cleaner than our current option using a bucket policy.
---
For more information, including how to check this deployment on preview or staging first before it …
=> Add support for blocking documents via S3 tagging

app/utils/store.py, tests/utils/test_store.py
If we get a different kind of boto error (eg NoSucKey), there may not be a ResourceType.
---
=> Don't expect ResourceType key

app/download/views.py
The views.py file did not have a http based health check. Instead it had the default port type health check on PaaS. 
These lines will allow AWS ecs to run the health check on the container and get an appropriate 200 status.
---
=> added status endpoint for download api

docker/Dockerfile, requirements.in, requirements.txt
=> Adds botocore[crt] python package and curl to the dockerfile

requirements.txt
Address https://nvd.nist.gov/vuln/detail/CVE-2023-28859 (doesn't apply to us anyway - we don't use async stuff)
---
=> Bump redis to 4.5.4

Makefile, requirements.in, requirements.txt
This bumps us quite a lot, but is really only to pull in the change from `logger.exception` to `logger.warning` on log-formatting errors.
Here's the full changelog diff though. None of the major version bumps are 
concerning.
* Change `logger.exception` to `logger.warning` for log formatting error.
* Adds support for Chinese character sets in letters
* Injects the celery task ID into logging output if no requestId is present.
* Add odd/even class to letter pages
* Allow extra logging filters to be passed into `notifications_utils.logging.init_app`.
* Add a `UserIdFilter` to automatically inject the user_id to flask request logs.
* Include the country for normalised BFPO lines.
* Updated PostalAddress to parse BFPO addresses. Any validation done on PostalAddresses should be update to …
=> Bump utils

Makefile, app/.gitignore, app/performance.py
Copies the 'generate-version-file' step that we have in API and admin, and uses that (if possible) when initialising Sentry. This will let us track releases and tie errors to new releases.
We'll need to update the deployment pipeline to generate this file, but that can happen separately.
---
=> Add version file make step; tag release for sentry

deploy-exclude.lst
We use this file in all of the other apps to exclude files from the zip archive that is used to deploy our apps.
---
=> Add deploy-exclude.lst

app/config.py
We had `FRONTEND_HOSTNAME` listed twice in the same class.
---
=> Remove duplicate variable

manifest.yml.j2
Initially this was failing with this error:
For application 'document-download-api': No domains exist for route download.documents.notify.works
When trying to create the `documents.notify.works` domain in cf we got:
The domain name "documents.notify.works" cannot be created because "documents.notify.works" is already reserved by a route
Trying to create the `download.documents.notify.works` domain in cf we got:
The domain name "download.documents.notify.works" cannot be created because "documents.notify.works" is already reserved by a route
The answer probably lies somewhere here: https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#parent-child-domains
---
For more information, …
=> Remove new preview route to unblock pipeline

app/config.py
When the apps run on ECS we need to connect to the S3 bucket via the multiregion accesspoint - we can't just put objects in S3 directly like we can when running on the PaaS. This change lets us optionally set a new variable, `MULTIREGION_ACCESSPOINT_ARN`, for running on ECS. If set, this should be the value of the accesspoint arn.
---
=> Update `DOCUMENTS_BUCKET` value for preview

Makefile, manifest-droplet.yml, scripts/create-droplet.sh, scripts/deploy.sh
At the moment we deploy the API app by building a CloudFoundry droplet and then copying that droplet to preview/staging/prod (broadly equivalent to building a docker image and deploying that). In our other apps, though, we build the droplet in each environment as deployments happen. This is both slower and in theory less reproducible, since each environment could have issues building the app or build things differently.
This copies across the relevant scripts from the API so that we can build the droplet once and promote it through each environment.
---
For more information, including how to check this deployment on preview or staging first before it goes to production, see our [team wiki section on …
=> Add create-droplet/deploy scripts

manifest.yml.j2
Bind the `donwload.` subdomain as route across all environments.
This will *not* serve any traffic yet.
---
=> Add `download.` route across all environments

app/config.py
We think we will need this for the ECS app to provide external links to itself
https://trello.com/c/Qy4JgJDD/293-make-the-document-download-functional-tests-pass
---
=> Allow configuration of SERVER_NAME env var for all environments

app/cloudfoundry_config.py
We realised our previous PR was only adding the `/1` for the redis URL provided by VCAP services. We also want to add the `/1` for the redis URL provided by the REDIS_URL environment variable (ie we have set it in our credentials repo).
---
=> Always use DB 1, regardless of which redis we are using

app/config.py, app/utils/urls.py, manifest.yml.j2, tests/conftest.py, tests/download/test_views.py, tests/upload/test_views.py, tests/utils/test_urls.py
When the app is deployed on the PaaS, document-download-frontend calls document-download-api on its public route and the `get_direct_file_url` function generates a URL using that public route. On ECS, document-download-frontend will use the private route, which results in the URLs generated using the private domains which we don't want.
We now create an environment variable, `DOCUMENT_DOWNLOAD_API_HOSTNAME`, and use when generating the URL of the file.
---
For more information, including how to check this deployment on preview or staging first before it goes to production, see our [team wiki section on deployment](https://github.com/alphagov/notifications-manuals/wiki/Merging-and-deploying#deployment …
=> Change how `get_direct_file_url` generates URLs

gunicorn_config.py
Review commit by commit but essentially
- small spacing tidy up
- set 90 second keepalive to match https://github.com/alphagov/notifications-admin/pull/4826
---
=> Set 90 second gunicorn keepalive

manifest-droplet.yml, manifest.yml.j2
What
----
Switch to use the PaaS cflinuxfs4 stack.
Why
----
cflinuxfs3 is currently the default on the PaaS. This is based off ubuntu 18.04. This stopped receiving updates after Apr 2023.
cflinuxfs4 will become the default on the PaaS after 27 Nov 2023.
The intention is to migrate all applications to cflinuxfs4 eventually.
---
=> Switch to use cflinuxfs4

manifest-droplet.yml, manifest.yml.j2
Reverts alphagov/document-download-api#273
The change of the underlying OS has pulled in an updated version of libmagic, which is detecting JSON better, resulting in us rejecting JSON data.
Doing this as a quick fix while we investigate and fix more properly.
```
vcap@cf5c2aad-e255-4091-60d2-d144:~$ apt show libmagic1
Package: libmagic1
Version: 1:5.32-2ubuntu0.4
Status: install ok installed
Priority: optional
Section: libs
Source: file
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Christoph Biedl <debian.axhn@manchmal.in-ulm.de>
Installed-Size: 204 kB
Depends: libc6 (>= 2.15), zlib1g (>= 1:1.1.4), libmagic-mgc (= 1:5.32-2ubuntu0.4)
Suggests: file
Homepage: http://www.darwinsys.com/file/
Download-Size: unknown
APT-Manual-Installed: yes …
```
=> Revert "Switch to use cflinuxfs4"

manifest.yml.j2
=> Set `REDIS_ENABLED` env var in the manifest if one is defined

requirements.txt
=> Bump sentry-sdk to 1.32.0

manifest.yml.j2
We had an outage recently due to PaaS rolling our antivirus instances without waiting for a replacement to come up.
This is not a fix, but would give paas more time to perform the roll successfully before potentially causing an outage for us.
The exact cause of the incident is unknown but may be down to slow docker image pull times from github during the app rolling.
---
We probably don't _need_ to bump doc-dl apps, because they're droplet-based rather than docker image-based, but the cost is minimal and if it gives us more confidence until we move to ECS then I think that's still worth it.
---
For more information, including how to check this deployment on preview or staging first before it goes to …
=> Bump min instance count to 3

Makefile, docker/Dockerfile, scripts/run_locally_with_docker.sh
We want to be able to run the tests in Docker since we saw differences in behaviour when running the app in Docker (on ECS) vs on the PaaS. The Dockerfile cannot be used for this without changes since it doesn't install any test dependencies.
This changes the Dockerfile to use multi-stage builds and to be as consistent as possible with those we have in other apps.
We can then run the tests in Docker
---
=> Change Dockerfile to use multi-stage builds and let tests be run in Docker

app/config.py
When running on ECS we set `DOCUMENTS_BUCKET` to be the `MULTIREGION_ACCESSPOINT_ARN` since we access the bucket through the multiregion accesspoint. We had made this change to preview, but this changes staging and production to match.
---
=> Change how we set `DOCUMENTS_BUCKET` in Staging and Production

app/upload/views.py, docker/Dockerfile, tests/sample_files/test_longer.csv, tests/upload/test_views.py, tests/utils/test_mime_types.py
**Add tests for a longer CSV file**
The test CSV file is very short (just one word) and we've seen slightly different behaviour with longer CSV files. This adds a second, longer, CSV file to the tests.
The behaviour of the two files in `test_document_upload_csv_handling` in inconsistent but this matches the current behaviour.
**Upgrade Dockerfile to use bookworm**
When this was using bullseye we were using libmagic-dev version 5.39 which has a known bug where CSV files can be identified as "application/csv" instead of registered "text/csv". By upgrading to Bookworm we get a later version of libmagic-dev without the bug.
After this change, the tests pass with Docker.
---
For more information, …
=> Upgrade to bookworm and add a longer CSV file for testing

requirements.in, requirements.txt
https://trello.com/c/Q5S5m4ge/446-add-http-logging-to-all-of-our-ecs-apps
See https://github.com/alphagov/notifications-utils/pull/1077, this should bring flask request logging to apps in desired circumstances.
---
=> requirements: notifications-utils: 66.0.0 -> 74.0.0

docker/Dockerfile
When document-download-api is running via its Dockerfile (ECS), we didn't have any mimetype files available. This change installs the package, which creates `/etc/mime.types`, which Python's `mimetypes` package reads.
This allows us to lookup all of the file extensions we support and convert them to mimetypes.
---
=> Install mime-support for extension lookups

app/utils/store.py, tests/utils/test_store.py
AWS S3 Metadata only accepts ASCII characters. In order to support rich
filenames, which may for example contains names with
characters/ligaments outside of the ASCII set, we can convert the utf-8
string to an ASCII respresentation, and undo that when pulling the
metadata back out of S3.
=> Handle UTF-8 filenames

app/config.py, app/utils/validation.py, tests/utils/test_validation.py
AWS S3 (User defined) metadata is limited to 2 KB in PUT requests, so we should make sure we're not using it all. I also want to not let filenames use the majority of it so that there's still space for us to use it for other things in the future, if we want.
By limiting filename length to 100 characters, we will in theory be allowing up to 580 bytes for the filename, assuming the extension (`.csv` takes up four and is always ASCII). The rest of the name could be unicode characters, which through encoding are converted to \Uxxxx - ie 6 bytes. So in the worst case, 96 UTF-8 characters will become 576 bytes. This is the extreme outlier, as I expect most filenames will be fully or mainly ASCII, so normally up to 100 bytes.
---
🚨⚠️ This will be deployed automatically all the way to production …
=> Limit custom filename length

docker/Dockerfile
From https://wiki.debian.org/mime-support
The `mime-support` package was split into two packages: `media-types`
and `mailcap`. `media-types` now provides the `/etc/mime.types` file.
`mailcap` associates media types with programs that can support them -
we don't need that, so we can probably just use `media-types` instead.
---
=> Change package for `/etc/mime.types`

app/utils/antivirus.py, tests/utils/test_antivirus.py
https://trello.com/c/n4FmWuff/585-annotate-logs-with-cloudfront-http-request-ids
A stopgap until we get proper universal tracing support going. At that point it can be removed.
---
=> AntivirusClient: include onwards request headers in requests

app/download/views.py, tests/download/test_views.py
We currently enforce automatic downloads of `csv` and `rtf` files. This PR does the same for `txt `files. 
---
=> Enable automatic download of txt files

requirements.in, requirements.txt
https://trello.com/c/n4FmWuff/585-annotate-logs-with-cloudfront-http-request-ids
* Include parent_span_id in request logs
* Include span_id in all logs when available
***
Complete changes: https://github.com/alphagov/notifications-utils/compare/74.5.0...74.6.0
---
=> Bump utils to 74.6.0

app/config.py, manifest.yml.j2, requirements.in, requirements.txt
flask-env makes it easy to run in to bugs where we think we're defining environment variable defaults but they're actually not used (for example, the REDIS_URL having a `/1` doesnt actually work because that just sets a value that flask-env then overwrites with the URL from the env later.
by removing it and just reading the env manually we can make our configs easier to reason about
previously, we expected to be passed in a REDIS_URL that looked like `rediss://some-domain:6379`, which we'd add `/1` to to use the second database contained on the redis server.
However we now use REDIS_DOCUMENT_DOWNLOAD_URL, which contains a /1 domain (and is defined variously in credentials for paas and in terraform for ecs).
Requires this to be merged first: 
---
🚨⚠️ This will be deployed automatically all …
=> Config cleanup

requirements.in, requirements.txt
=> Bump utils to 7.11.0

docker/Dockerfile
If `HOME` is not set it defaults to `/home/notify` which gives an error when trying to run `make freeze-requirements` of "The directory '/home/notify/.cache/pip' or its parent directory is not owned or is not writable by the current user."
---
=> Set `HOME` in Dockerfile test build

.pre-commit-config.yaml
I forgot to do the comment in
https://github.com/alphagov/document-download-api/pull/320/files that says to update pre-commit-config when upgrading our black version
---
=> Make precommit file match installed black version

gunicorn_config.py, requirements.in, requirements.txt
Reverts alphagov/document-download-api#322
Ugh statsd shouldn't be enabled for this app and the statsd config got included in the common gunicorn configuration
=> Revert "gunicorn structured logging"

app/config.py, app/download/views.py, requirements.in, requirements.txt
https://trello.com/c/kuPbusFR/724-check-if-we-should-and-then-remove-notifyruntimeplatform-functionality
~Depends on https://github.com/alphagov/notifications-utils/pull/1109 (though actually doesn't technically require it)~
---
=> remove use of `NOTIFY_RUNTIME_PLATFORM` & `NOTIFY_LOG_PATH` flask config parameters

app/config.py
So we actually get request logs
Akin to https://github.com/alphagov/notifications-antivirus/pull/162
---
=> config: set `NOTIFY_REQUEST_LOG_LEVEL` to `INFO`

app/utils/antivirus.py, app/utils/authentication.py, app/utils/files.py, app/utils/store.py, app/utils/urls.py, requirements.in, requirements.txt, tests/conftest.py, tests/utils/test_store.py
* Switches on Pyupgrade and a bunch of other more opinionated linting rules
* Bumped minimum versions of select subdependencies
* Restrict postcodes to valid UK postcode zones
***
Complete changes: https://github.com/alphagov/notifications-utils/compare/78.0.0...79.0.0
---
=> Bump utils to 79.0.0

requirements.in, requirements.txt
It was removed by mistake:
https://github.com/alphagov/document-download-api/pull/340/commits/25262ea9a180af3cf61bb332598dbf917cd24ae4#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552L137
---
=> Restore Sentry dependency

app/config.py, requirements.in, requirements.txt
What
----
- Include notify-environment for logging.
- Bump notifications-utils
---
=> Bump notifications-utils plus add environment config variable

.gitignore, requirements_for_test_common.txt
We excluded this file from version control because it’s copied automatically from utils, so we only need to modify it and track changes there. In theory at least.
In practice Dependabot cannot:
- cope with having a requirements file which isn’t in the repo
- be configured to only look at certain requirements files
So I think the best thing to do is keep this file in version control. It already has an automatically generated comment to suggest it shouldn’t be edited manually.
Dependabot may try to raise PRs against it, but we can resolve these by updating the upstream version in utils. We can then roll out several version bumps in a single PR per app, rather than several.
---
For more information, …
=> Version control requirements_for_test_common.txt

app/__init__.py, application.py, gunicorn_config.py
Also catch `EventletTimeout` exceptions, turning these into 504s, which are the closest thing to an application timeout standard codes seem to cover.
30s timeout as this is what we've decided to set our cloudfront/ALB timeouts to (we'll make this change shortly).
In `EventletTimeoutMiddleware`'s current implementation, the timeout gets cancelled as soon as the initial status response is returned, so streaming responses shouldn't be affected any more than normal responses.
p.s. where are the rest of our error handlers for this app?
Passes dev-a @ https://concourse.notify.tools/teams/dev-a/pipelines/deploy-notify/jobs/test/builds/59
---
For more information, including how to check this deployment on …
=> application: use `EventletTimeoutMiddleware` if using eventlet

requirements.in, requirements.txt
Incorporating https://github.com/alphagov/notifications-utils/pull/1160
---
=> notifications-utils: 87.0.0 -> 87.1.0

requirements.in, requirements.txt
Incorporating https://github.com/alphagov/notifications-utils/pull/1161
---
=> notifications-utils: 87.1.0 -> 88.0.1

requirements.in, requirements.txt
Incorporating https://github.com/alphagov/notifications-utils/pull/1162
---
=> notifications-utils: 88.0.1 -> 88.1.0

.pyup.yml
In most of our apps (for example [admin](https://github.com/alphagov/notifications-admin/blob/642c8f34a2045f9227252cef1b7759e6e82c1b73/.pyup.yml) and [api](https://github.com/alphagov/notifications-api/blob/62305c6e00f50ddeb321a2b6bd432407f941b11e/.pyup.yml)) we have PyUp configured to look at `requirements.in` and `requirements_for_test.txt` 
This means we’ll only get warnings about direct dependencies (the ones we specify).
In document-download-api we specify `requirements.txt` as well, meaning we also get warnings about indirect dependencies.
This commit makes document download consistent with the admin and API apps to reduce the amount of noise.
Also worth noting that `requirements-dev.txt` and `requirements-app.txt` no longer exist.
---
🚨⚠️ This will be deployed automatically all the …
=> Match pyup config to admin and API

docker/Dockerfile
> By default, uv does not compile Python (.py) files
> to bytecode (__pycache__/*.pyc); instead, compilation
> is performed lazily the first time a module is imported.
> For use-cases in which start time is critical, such as
> CLI applications and Docker containers, this option can
> be enabled to trade longer installation times for faster
> start times.
Without this we will see increased startup times for apps which can in turn break the dev envs, where instances have reduced cpu and can’t compile all their bytecode in time to return a healthcheck.
---
For more information, including how to check this deployment on preview or staging first before it goes to production, see our [team wiki section on …
=> Dockerfile: set UV_COMPILE_BYTECODE=1

.pre-commit-config.yaml, gunicorn_config.py, requirements.in, requirements.txt, requirements_for_test.txt, requirements_for_test_common.in, ruff.toml
* Bump minimum jinja2 version to 3.1.6 (closes #372)
* Fix external link redirect
* Fix QR code URL with '&' encoded as '&amp;'
* for bilingual letters preview, only show barcodes on the first page (patch).
* rename `include_notify_tag` argument to `includes_first_page` (major).
* BREAKING CHANGE: the `gunicorn_defaults` module has been moved to `gunicorn.defaults` to make space for gunicorn-related utils that don't have the restricted-import constraints of the gunicorn defaults. Imports of `notifications_utils.gunicorn_defaults` should be changed to `notifications_utils.gunicorn.defaults`.
* Added `ContextRecyclingEventletWorker` custom gunicorn worker class.
* Implement `InsensitiveSet.__contains__`
* Fix to the number of arguments the `on_retry` of the `NotifyTask` class takes.
*** …
=> Bump utils to 97.0.3

requirements.txt, requirements_for_test.txt
The version of Gunicorn we are using is more than 18 months out of date<sup>1</sup> and has a high severity security vulnerability<sup>2</sup>.
We have not updated the version on the API (and therefore the minimum version in utils<sup>3</sup>) because last time we tried (while still on PaaS) it had some performance issues, documented here<sup>4</sup>:
> We originally pinned this due to eventlet v0.33 compatibility issues. That was supposedly fixed in version v21.0.0 and we merged v21.2.0 for a while. Until we ran a load test again, and identified that the bumped version of gunicorn led to a 33%+ drop-off in performance/requests per second that the API was able to handle. If a version greater than 21.2.0 is released, and it either gives us something we need or we think it addresses said …
=> Bump gunicorn to the latest version

.pre-commit-config.yaml, requirements.in, requirements.txt, requirements_for_test.txt, requirements_for_test_common.in, ruff.toml
Bump utils to 100.2.0
* add  fields to pre/post request flask logs
* Updated  to version 9.0.9 to keep phonenumber metadata uptodate
*  is now a required argument of  (apps have already been updated)
* Add new version of GOV.UK brand to email template, behind a flag
* Update economy letter transit dates to max 8 days
* Improve celery json logging. Include beat with separate log level options and testing
* Make inheritence of annotations on SerialisedModel work on both the class and its instances
***
Complete changes: https://github.com/alphagov/notifications-utils/compare/99.5.1...100.2.0
=> chore: bump utils to 100.2.0

requirements.txt, requirements_for_test.txt
The versions we are using do not install on newer versions of Python because of the way they are packaged.
Change already deployed in other repos, for example: https://github.com/alphagov/notifications-api/pull/4486
=> Bump greenlet and cffi to the latest versions

app/utils/file_checks.py, tests/file_checks/test_views.py
Things which don’t change the results of the MIME type check:
- anything in the filename, apart from the extension
- the `is_csv` argument, if a filename is provided 
This commit makes it so these things don’t vary the hash key. This probably won’t result in a speedup but it could result in slightly fewer cache keys being put in Redis.
=> Optimise hash key for MIME type check
